version: '3'
services:
  molecule:
    build: .
    image: entercloudsuite/molecule
    volumes:
        - ./src:/root/src
        - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root/src